### ISSUE TITLE
Containers deployment

### ISSUE THREAD

**Issue by razaleighwiseman** [nishi2go/maximo-docker#10]
Hi,

After successfully built all the required images, I run `docker-compose up -d` to create and deploy instances.

How do I know the setup has been completed? 

The console only show few lines stated that starting containers. 

![image](https://user-images.githubusercontent.com/24619644/59731829-469efa00-927a-11e9-8036-310d08ac8364.png)

Thank you

**Comment by nishi2go** [comment]
Hi,

This is not an issue because it is a question for general usage of docker compose. Please check the documentation, https://docs.docker.com/compose/

Thanks

**Comment by razaleighwiseman** [comment]
Hi,

Noted. Does it mean the setup is running? 

Thank you

**Comment by razaleighwiseman** [comment]
Hi,

Got it. I use -f to follow log output in console during startup.

Thanks
