### ISSUE TITLE
Maximo Sample Data

### ISSUE THREAD

**Issue by razaleighwiseman** [nishi2go/maximo-docker#11]
Hi,

How do I enable sample data to be included in the application during the installation?

Thanks in advance

**Comment by nishi2go** [comment]
Hi,

Turn ENABLE_DEMO_DATA to yes in https://github.com/nishi2go/maximo-docker/blob/master/docker-compose.yml

**Comment by razaleighwiseman** [comment]
Hi,

Got it.

Thanks a lot
