### ISSUE TITLE
Maximo Add-ons

### ISSUE THREAD

**Issue by razaleighwiseman** [nishi2go/maximo-docker#12]
Hi,

Is it possible to install add-on on the existing container. Or need to modify the dockerfile to achieve the result?

For example if I want to include add-ons such as Maximo APM Asset Health Insights, Scheduler, Scheduler Plus, HSE, Anywhere, Linear Asset Manager and etc. Is that possible

Please advice.

Thanks in advance

**Comment by nishi2go** [comment]
Yes, modify or extend (by using FROM) the dockerfile and then deploy the new image. I believe you don't need to refresh whole image, just only deploy the maximo (installer) image.
