### ISSUE TITLE
Guidance on using repo but replacing DB2 with SQL Server

### ISSUE THREAD

**Issue by lhchang** [nishi2go/maximo-docker#13]
Hello, 
I am interested in using this Docker setup that you have constructed, but instead of using DB2 we wanted to replace it with SQL Server. We have made a SQL Server image that as far as I can tell is configured according to the Maximo Database Manual Configuration document for SQL Server. Furthermore, we have modified the existing scripts provided and Dockerfiles to match our SQL Server Dockerfile and configs. As far as the install, things seem to be going well according to the Docker logs until maximo_1 does the updateApplication action. Do you have any guidance or suggestions on where we may look to overcome this error?

```maximo_1   | CTGIN5149I: The process automation engine configuration service received the following command: "-action updateApplication -updatedb -deploymaximoear -enableSkin iot18 -enableEnhancedNavigation ".
maximo_1   | CTGIN5386I: Updating the database to the latest level.
maximo_1   | CTGIN5368E: An unexpected error occurred while obtaining the status of the application.
maximo_1   | CTGIN5387I: The database update is complete.
maximo_1   | CTGIN5013E: The reconfiguration action UpdateApplication failed. Refer to messages in the console for more information.
maximo_1   | WASX7209I: Connected to process "dmgr" on node ctgCellManager01 using SOAP connector;  The type of process is: DeploymentManager
maximo_1   | Error importing re.
maximo_1   | Error importing glob.
maximo_1   | Error importing os.path.
maximo_1   | Error importing getopt.
maximo_1   | Error importing traceback.
maximo_1   | [2019-1218-2241-4100] enableDebugMessages Verbose trace messages are now enabled; future debug messages will now be printed.
maximo_1   | [2019-1218-2241-4600] startServer: server ctgNode01,MXServer is already running
maximo-docker_maximo_1 exited with code 0```

**Comment by nishi2go** [comment]
Hi,
It seems DB configuration was failed after updatedb.sh script passed. There were anything wrong configurations around the DB service. But you need to get installation logs under /opt/IBM/SMP/ConfigTool/logs directory to get more information. You can obtain them with "docker cp" command from live containers. To keep the "maximo" container live, set KEEP_RUNNING env variable to yes in docker-compose.yml.

**Comment by lhchang** [comment]
Got it working - it wasn't liking the URL so just had to fix that. Thanks for the help!
