### ISSUE TITLE
Linux distros that work best for maximo-docker?

### ISSUE THREAD

**Issue by fogoat** [nishi2go/maximo-docker#4]
Hello, can you explain which Linux distro you tested docker with? Would Red Hat 7 work? I apologize if this is a silly question because docker should really abstract the OS level right?

**Comment by nishi2go** [comment]
I've tested on Ubuntu 16.04, Docker for Windows and Mac. I'd recommend Ubuntu because its performance is better than Windows and Mac due to without Hypervisor layer like Hyper-V.

**Comment by johnposten** [comment]
I have also ran it on Ubuntu 16.04 with good results.
