### ISSUE TITLE
How to enable RMI

### ISSUE THREAD

**Issue by johnposten** [nishi2go/maximo-docker#6]
What is the best way to go about enabling the RMI interface on the deployed application?  I have tried adding `mxe.rmi.host` and `mxe.rmi.registry` to the 'Maximo Configuration Parameters' section of `maximo/startinstall.sh`, but that doesn't seem to work.

Also, which dockerfile would I `EXPOSE` these ports in?

**Comment by nishi2go** [comment]
If you want to edit maxim.properties, add a line to add them after the line 114 as follows:
L.113
```
/opt/IBM/SMP/ConfigTool/scripts/reconfigurePae.sh -action updateApplication \
-updatedb -deploymaximoear -enableSkin tivoli13 -enableEnhancedNavigation

echo "mxe.rmi.port=2099" >> /opt/IBM/SMP/maximo/applications/maximo/properties/maximo.properties

# Update and deploy maximo.properties
/opt/IBM/SMP/ConfigTool/scripts/reconfigurePae.sh -action updateApplication \
-updatedb -deploymaximoear -enableSkin tivoli13 -enableEnhancedNavigation
```

For exposing its port, edit "ports" section of maxapps in docker-compose.yml.

**Comment by johnposten** [comment]
I was forgetting about the ports section in docker-compose.yml.  Thanks that part worked great!

Adding the line for `mxe.rmi.port` doesn't seem to be working.  When I go to System Properties it still shows the default value of 0.  Shouldn't these values be set before the ear is deployed?

**Comment by nishi2go** [comment]
@johnposten OK, try the following command instead of echo.

```
/applications/maximo/properties/maximo.properties
/opt/IBM/SMP/ConfigTool/scripts/reconfigurePae.sh -action updateApplication \
-updatedb -deploymaximoear -enableSkin tivoli13 -enableEnhancedNavigation

sed -i "s/mxe.rmi.port=.*/mxe.rmi.port=2099/"  /opt/IBM/SMP/maximo/applications/maximo/properties/maximo.properties

# Update and deploy maximo.properties
/opt/IBM/SMP/ConfigTool/scripts/reconfigurePae.sh -action updateApplication \
-updatedb -deploymaximoear -enableSkin tivoli13 -enableEnhancedNavigation
```

**Comment by johnposten** [comment]
That did seem to work.  Thank you for the help.
