### ISSUE TITLE
IBM Maximo

### ISSUE THREAD

**Issue by Marcaf** [nishi2go/maximo-docker#8]
Could you provide part numbers of Maximo  which are required by this project

**Comment by nishi2go** [comment]
CJ41KML according to https://www-356.ibm.com/partnerworld/wps/servlet/download/DownloadServlet?id=uruRYDTrjaWiPCA$cnt&attachmentName=Software_Access_Catalog_sample_list.pdf&token=MTU1Mjg3NDc5Nzk5Mw==&locale=en_ALL_ZZ
