### ISSUE TITLE
db2 Image build failed

### ISSUE THREAD

**Issue by razaleighwiseman** [nishi2go/maximo-docker#9]
I'm not able to build the db2 image. Process stopped at step 35;

Step 35/45 : RUN wget -q $url/$DB2_IMAGE   && bsdtar -zxpf $DB2_IMAGE   && ./server_awse_o/db2setup -r ./db2awse.rsp   && /opt/ibm/db2/V11.1/adm/db2licm -a ./server_awse_o/db2/license/db2awse_o.lic   && /opt/ibm/db2/V11.1/adm/db2licm -l   && rm -rf *
 ---> Running in 1285867096a2
The command '/bin/sh -c wget -q $url/$DB2_IMAGE   && bsdtar -zxpf $DB2_IMAGE   && ./server_awse_o/db2setup -r ./db2awse.rsp   && /opt/ibm/db2/V11.1/adm/db2licm -a ./server_awse_o/db2/license/db2awse_o.lic   && /opt/ibm/db2/V11.1/adm/db2licm -l   && rm -rf *' returned a non-zero code: 4

Please help.

Thanks in advance

**Comment by razaleighwiseman** [comment]
Also identical error when attempt to build installation manager image;

Step 9/10 : RUN mkdir /Install_Mgr && wget -q $url/$IM_IMAGE  && unzip -q -d /Install_Mgr $IM_IMAGE  && rm $IM_IMAGE  && /Install_Mgr/EnterpriseDVD/Linux_x86_64/EnterpriseCD-Linux-x86_64/InstallationManager/installc -log /tmp/IM_Install_Unix.xml -acceptLicense  && rm -rf /Install_Mgr
 ---> Running in 879f2f1a5442
The command '/bin/sh -c mkdir /Install_Mgr && wget -q $url/$IM_IMAGE  && unzip -q -d /Install_Mgr $IM_IMAGE  && rm $IM_IMAGE  && /Install_Mgr/EnterpriseDVD/Linux_x86_64/EnterpriseCD-Linux-x86_64/InstallationManager/installc -log /tmp/IM_Install_Unix.xml -acceptLicense  && rm -rf /Install_Mgr' returned a non-zero code: 4

Do I need to modify the docker file?

Thanks in advance

**Comment by nishi2go** [comment]
Hi,

This is a network related error in wget. Please make sure the nginx container has been started.

Thanks,

**Comment by razaleighwiseman** [comment]
Hi,

Yes, the nginx container is running. However still get above error.

Note: docker run --name images -h images --network build \
-v [Image directory]:/usr/share/nginx/html:ro -d nginx

Which directory is [Image directory] refer to?

**Comment by nishi2go** [comment]
Hi,

You must specify the directory including required packages - https://github.com/nishi2go/maximo-docker#required-packages. Please check the binaries are available before running build commands.

Thanks

**Comment by razaleighwiseman** [comment]
Hi,

Thanks for the clarification. Both containers are successfully built

Thank you.
